//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RepublicaGalacticaEntities1 : DbContext
    {
        public RepublicaGalacticaEntities1()
            : base("name=RepublicaGalacticaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Especie> Especies { get; set; }
        public virtual DbSet<Galaxia> Galaxias { get; set; }
        public virtual DbSet<Maestro> Maestroes { get; set; }
        public virtual DbSet<MiembrosConsejo> MiembrosConsejoes { get; set; }
        public virtual DbSet<OrdenJedi> OrdenJedis { get; set; }
        public virtual DbSet<Padawan> Padawans { get; set; }
        public virtual DbSet<Planeta> Planetas { get; set; }
        public virtual DbSet<Sistema> Sistemas { get; set; }
        public virtual DbSet<SistemasAmenazado> SistemasAmenazados { get; set; }
    
        public virtual ObjectResult<Informe_Result> Informe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Informe_Result>("Informe");
        }
    }
}
